### ISSUE TITLE
Slow performance on single node with 4 receivers

### ISSUE THREAD

**Issue by ajukraine** [Azure/azure-event-hubs-node#1]
I have event hub with 4 partitions (and 4 TPU) with 2500 events per each partition.

I've executed script in single Node.js instance, which creates 4 receivers. Total execution time is 3m2.943s
After that I've executed simultaneously 4 instances, each had 1 receiver. The average execution time is 56s.

Also I have C# .NET application, which creates 4 receivers (each in separate thread). Total execution time is 58s.

Question: Why single Node.js instance cannot meet the execution time of the multi-threaded C# .NET application? Is it possible to implement non-blocking reading from multiple partitions in Node.js?

**Comment by amarzavery** [comment]
@ajukraine - We have a new preview version "0.1.0" of the event hubs node.js client. This client was re-written from scratch. Please try the new version and let us know if you still see issues. You can find examples over [here](https://github.com/Azure/azure-event-hubs-node#examples).
