### ISSUE TITLE
please handle transient errors (!)

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/azure-event-hubs-node#10]
Errors such as `AmqpMessagePublisher.IdleTimerExpired` are thrown without proper error handling causing the client as well as our own code to crash.  This is fundamentally critical... 

ping @mrohera @jtaubensee

**Comment by amarzavery** [comment]
@1N50MN14  - Yes, we do handle transient errors. We have a new preview version "0.1.0" of the event hubs node.js client. This client was re-written from scratch. Please try the new version and let us know if you still see issues. You can find examples over [here](https://github.com/Azure/azure-event-hubs-node#examples).
