### ISSUE TITLE
Need browser friendly versions of node.js iot modules - client can't connect to iot hub

### ISSUE THREAD

**Issue by rricart** [Azure/azure-event-hubs-node#11]
Trying to implement a device-to-cloud receiver on browser.  Console code in "Get started with IoT Hub (Node)" documentation works fine.  Encountered following errors on browser:

1.	node module: azure-iot-common -> lib\authorization.js :: runtime error - crypto.createHmac is not a function.
•	we changed reference of crypto to crypto-browserify in this file and installed crypto-browserify node module in root directory, which resolve that error.
2.	After 1 was resolved then we got the following  - node module: azure-event-hubs -> node_modules\amqp10\lib\transport\tls_transport.js :: runtime error - tls.connect is not a function.
•	we changed reference of tls to tls-browserify in this file and installed tls-browserify node module in root directory, which resolve the error.
3.	After 2 resolve then we got the following - node module: tls-browserify -> index.js :: runtime error net.Socket is undefined. 
•	we changed reference of net to net-browserify and installed the module in root directory, which solved the problem.
4.     Now the while opening the connection at run time we are getting "cannot open TCP connection" error:
    let client = Client.fromConnectionString(connectionString);
    client.open()      <---- error thrown here
         .then(client.getPartionIds.bind(client)
         .then(function(partitionIds){ .....
Note: we will then try to implement a simulated device on the browser and must have browser friendly versions of azure-iothub, azure-iot-device, and azure-iot-device-amqp or mqtt

**Comment by olivierbloch** [comment]
Hi @rricart , at this point the Azure IoT Hub service doesn't support CORS (Cross-Origin Resources Sharing), which I think will anyways prevent the code running in the browser client to establish the TCP connection with IoT Hub.
This feature is in our plan of record but we don't have an ETA for it yet.
To help out prioritize the feature and help unblock you with an alternative, can you please share what the scenario is that you are trying to implement?
Thanks

**Comment by rricart** [comment]
I was afraid that was the issue.  I looked in the portal and there was no setting for CORS.  We have developed the following in AWS and tried to do it in Azure but encountered the putative CORS issues.  The clients are very interested in Azure.  These apps are POCs and demos that we use for sales.  Is there any way to expedite this?  An IoT device should be anything.

The scenario is one where we need to have the ability to send synchronous HTTP requests to an order processing system and be able to receive order updates asynchronously via the IoT Hub.  The browser application plays the role of an IoT device that receives messages to it from the order processing center.  There is a counterpart at the order processing center that receives asynchronous messages as well from the order processing system.  The latter plays the role of an IoT device that updates the order processing app.  The order processing app receives device-to cloud messages.


Rick Ricart
Azure Cloud Lead
[http://accenture.emsecure.net/images/2012/signatures/signature-logo.jpg]
Email: richard.ricart@accenture.com<mailto:richard.ricart@accenture.com>
Cell: +1 321-544-4000
Lync: +1 727-897-7038

**Comment by fbertilsson** [comment]
Hi,

I too, have been struggling with the node libraries in the browser. I abandoned it and decided to try REST which I now find out is not possible.

This would be a great feature. Write a web site and send data to the cloud. I hope this will be possible soon. I believe it would speed up adoption and creativity!

At least, add the CORS support. That should be real quick.

Thanks,
Fredrik
