### ISSUE TITLE
connectionString parameter for createConnectionFromString isn't accepted regardless of type

### ISSUE THREAD

**Issue by TheWispy** [Azure/azure-event-hubs-node#111]
**Describe the bug**
> Error: 'connectionString' is a required parameter and must be of type: 'string'.
> at Function.createFromConnectionString (/home/will/Documents/eventhub-puller/node_modules/azure-event-hubs/dist/lib/eventHubClient.js:203:19)
> at Function.createFromConnectionString (/home/will/Documents/eventhub-puller/node_modules/azure-event-processor-host/dist/lib/eventProcessorHost.js:292:108)
> at /home/will/Documents/eventhub-puller/index.js:53:75

**To Reproduce**
Run examples/eph.ts with tsc --lib ES2015 and then node eph.js. Connection strings are set with a .env file and dotenv. Regardless of whether the first string is declared with _createHostName_ or as _"string"_ it will through the same error.

**Expected behavior**
A connection to be opened

**Package-name**: **azure-event-hubs** | **azure-event-processor-host**
**Package-version**: 0.1.4
**node.js version**: 8.10.0
**OS name and version**: Ubuntu 18.04

**Comment by amarzavery** [comment]
This has been fixed with the new package @azure/event-processor-host.
