### ISSUE TITLE
run long-running scenario tests without issues

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-event-hubs-node#125]
1. ClientSenderSendReceive - Generic send and receive on client.
2. HighThroughput - Runs on a 100TU namespace and saturates ingress.
3. HighThroughputPartitionSender - Runs on a 100TU namespace and saturates ingress with partition senders.
4. EphShuffleHostsLargeShards - Registers and unregisters hosts as part of the regular iteration to introduce excessive partition moves. No sends in this scenario.
5. EphLargeShards - Runs EPH on 256 partition entity.

**Comment by amarzavery** [comment]
### ClientSenderSendReceive - Generic send and receive on client.

<img width="1130" alt="screen shot 2018-08-08 at 7 26 25 pm" src="https://user-images.githubusercontent.com/4521223/43874499-05bc3cea-9b41-11e8-8474-be8ed8b179a0.png">

**Comment by amarzavery** [comment]
### EphShuffleHostsLargeShards - Registers and unregisters hosts as part of the regular iteration to introduce excessive partition moves. No sends in this scenario.

Ran the test by starting with 3 EPH instances. It was able to balance the load effectively across 256 partitions. Later brought 1 EPH instance down and the load was balanced effectively again.
