### ISSUE TITLE
client.receiveBatch method silently exiting the process, if the network is disconnected in the mid of receiving messages.

### ISSUE THREAD

**Issue by arulselvam** [Azure/azure-event-hubs-node#130]
`client.receiveBatch` method silently exiting the process, when the network is disconnected in the mid of receiving messages.

**To Reproduce**
Call `await client.receiveBatch(…)` in a loop with try catch handlers. 
Disconnect the network while started receiving messages. 

**Expected behavior**
`await client.receiveBatch(…)` should throw any exception to the calling code, instead it's currently terminating the process.

**Package-name**: **azure-event-hubs**
**Package-version**: 0.2.6
**node.js version**: 10.0.0
**OS name and version**: Windows 10

**Comment by amarzavery** [comment]
Interesting, can you please provide the debug logs? That would help us figure out the problem.
Set the environment variable and you should be able to see the debug logs
```bash
set DEBUG=azure*,rhea*,-rhea:raw,-rhea:message,-azure:amqp-common:datatransformer
```

**Comment by arulselvam** [comment]
Pasting the tail of debug logs. Let me know if you want the entire debug log.
```
2018-08-14T18:24:57.111Z rhea:events [connection-1] Link got event: message

2018-08-14T18:25:16.895Z azure:event-hubs:receiverbatching [connection-1] Batching Receiver '34465cad-8ca6-4914-becc-a47f0a0b9f85'  
max wait time in seconds 20 over.

2018-08-14T18:25:16.896Z azure:event-hubs:error [connection-1] Deleted the receiver '34465cad-8ca6-4914-becc-a47f0a0b9f85' from the 
client cache.

2018-08-14T18:25:16.896Z rhea-promise:error [connection-1] The receiver is open ? -> true

2018-08-14T18:25:16.896Z rhea:frames [connection-1]:1 -> detach#16 {"closed":true} 

2018-08-14T18:25:36.302Z rhea:events [connection-1] Connection got event: disconnected

2018-08-14T18:25:36.302Z azure:event-hubs:error [connection-1] Error (context.error) occurred on the amqp connection: { Error: read 
ECONNRESET
    at TLSWrap.onread (net.js:659:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```

**Comment by arulselvam** [comment]
Pasting the tail of debug logs. Let me know if you want the entire debug log.
```
2018-08-14T18:24:57.111Z rhea:events [connection-1] Link got event: message

2018-08-14T18:25:16.895Z azure:event-hubs:receiverbatching [connection-1] Batching Receiver '34465cad-8ca6-4914-becc-a47f0a0b9f85'  
max wait time in seconds 20 over.

2018-08-14T18:25:16.896Z azure:event-hubs:error [connection-1] Deleted the receiver '34465cad-8ca6-4914-becc-a47f0a0b9f85' from the 
client cache.

2018-08-14T18:25:16.896Z rhea-promise:error [connection-1] The receiver is open ? -> true

2018-08-14T18:25:16.896Z rhea:frames [connection-1]:1 -> detach#16 {"closed":true} 

2018-08-14T18:25:36.302Z rhea:events [connection-1] Connection got event: disconnected

2018-08-14T18:25:36.302Z azure:event-hubs:error [connection-1] Error (context.error) occurred on the amqp connection: { Error: read 
ECONNRESET
    at TLSWrap.onread (net.js:659:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```

**Comment by amarzavery** [comment]
I see. What is going on. So when receiveBatch is complete, in the end it closes the receiver link. There is no timeout on the promise to close the receiver link. Hence that pomise does not resolve (reject in this case). On the other hand, the connection gets a disconnected event. The `disconnected` event handler, logs the error, but there is nothing to do since there are no receivers present in the cache that need to be recovered. Thus the program silently fails.

In an ideal situation when the network connectivity is there, after sending the `detach#16` frame, a response from the service would be received from the service. After which the Promise resolves.
```bash
 azure:event-hubs:receiverbatching [connection-1] Batching Receiver '176e05dc-b9bd-45c4-a496-9080a1163d2e'  max wait time in seconds 20 over. +20s
azure:event-hubs:error [connection-1] Deleted the receiver '176e05dc-b9bd-45c4-a496-9080a1163d2e' from the client cache. +20s
  rhea-promise:error [connection-1] The receiver is open ? -> true +21s
  rhea:frames [connection-1]:1 -> detach#16 {"closed":true}  +20s
  rhea:io [connection-1] read 17 bytes +20s
  rhea:io [connection-1] got frame of size 17 +0ms
  rhea:frames [connection-1]:1 <- detach#16 {"closed":true}  +77ms
  rhea:events [connection-1] Link got event: receiver_close +20s
  rhea-promise:receiver [connection-1] Resolving the promise as the amqp receiver has been closed. +21s
  rhea-promise:receiver [connection-1] receiver has been closed, now closing it's session. +0ms
  rhea-promise:error [connection-1] The session is open ? -> true +79ms
  rhea-promise:session [connection-1] Calling session.close() +20s
  rhea:frames [connection-1]:1 -> end#17 {}  +1ms
  rhea:io [connection-1] read 15 bytes +78ms
  rhea:io [connection-1] got frame of size 15 +0ms
  rhea:frames [connection-1]:1 <- end#17 {}  +77ms
  rhea:events [connection-1] Session got event: session_close +78ms
  rhea-promise:session [connection-1] Resolving the promise as the amqp session has been closed. +77ms
  azure:event-hubs:linkEntity [connection-1] BatchingReceiver '176e05dc-b9bd-45c4-a496-9080a1163d2e' with address 'test1/ConsumerGroups/$default/Partitions/0' closed. +20s
```

I am in the middle of finishing another high priority task and will fix this in the next 2-3 weeks. 

Moreover, I feel this is an edge case scenario. Let me know if you think otherwise.

**Comment by arulselvam** [comment]
We are planning to use this sdk for production in couple of weeks.   Not sure how frequently network glitches occurs in Azure, if it occurs frequently then it may not be an edge case.
I'll use the sdk in the test envrionment for a week and update you if we are facing application crashes due to this issue.

**Comment by amarzavery** [comment]
@arulselvam - Did you see any issues with receiveBatch due to network glitches? Just checking to ensure the experience is smooth.

**Comment by arulselvam** [comment]
@amarzavery , just 2 days before we deployed our app with 0.2.6 version. So far haven't faced any issues with receiveBatch.

**Comment by amarzavery** [comment]
Couple more issues were fixed with disconnects. Please feel free to install 0.2.8 version of the sdk. Feel free to reopen the issue if problem persists.

**Comment by amarzavery** [comment]
@arulselvam - We have released a stable version of the event hubs package. With this, we have moved to publishing packages under @azure org on npm. Current "azure-event-hubs" package has been deprecated. The new package is "@azure/event-hubs". Just wanted to let you know about this.

**Comment by arulselvam** [comment]
@amarzavery, thanks, great news. deployed the new bits to our test environment yesterday, it's working fine so far.
