### ISSUE TITLE
The 0.2.4 release silently bumbed version of Node runtime dependency and broken some Azure sample apps

### ISSUE THREAD

**Issue by peterblazejewicz** [Azure/azure-event-hubs-node#131]
**Describe the bug**
> A clear and concise description of what the bug is.
https://github.com/Azure-Samples/web-apps-node-iot-hub-data-visualization/issues/19
> In the 0.2.4 version the azure-event-hubs added undocumented use of async/await, which bumbed the minum required version of Node to 7.6:

> https://github.com/Azure/azure-event-hubs-node/releases/tag/v0.2.4-EH-July2018
> https://github.com/Azure/azure-event-hubs-node/blob/v0.2.4-EH-July2018/client/lib/rhea-promise/connection.ts#L179
> Azure/azure-event-hubs-node@d367b2a#diff-f2311358a38bc41bc8d4393e0c733a97R7

You've bumped the TypeScript compiler output runtime version to `es2017`, so now default Azure Node version is out of equation (6.9.1 AFAIK) as most of MS samples for Node do not use frozen packages versions  created with --save-exact flag.

To fix the problem users are forced to manually update Node version within the Azure portal.

**To Reproduce**
From the customers point of view:
- follow MS docs to run Azure IoT sample: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-raspberry-pi-kit-node-get-started
- wonder why the app renders nothing or what is the syntax error reported in console (which is not directly pointing to async/await runtime not being supported with current Node runtime):
https://github.com/Azure-Samples/web-apps-node-iot-hub-data-visualization/issues/17

Thanks!

**Comment by amarzavery** [comment]
Thanks for letting us know.

Some context:
It is recommended to use a version from the LTS release. Right now the LTS release is 8.x. In October this year, the LTS release would move to 10.x. Thus node.js version 6.x will soon be ancient. You can find the  node.js release schedule [here](https://github.com/nodejs/Release#release-schedule).

Azure App Service supports several versions of node.js. However, it enables customers to set one of the newer versions from the LTS release (currently 8.11.1) as the default version of node.js. You should be able to set the default version of node.js on the web app by setting the application setting `WEBSITE_NODE_DEFAULT_VERSION`. [This blog post](http://hardcoded.se/2015/01/07/node-js-version-on-azure-websites/) can be useful.

You should be able to find out the supported versions of the node.js runtime on your app service from here: https://<your-web-app-name>.scm.azurewebsites.net/api/diagnostics/runtime. By going here https://<your-web-app-name>.scm.azurewebsites.net, you can find other useful information about your environment and

**Comment by ramya-rao-a** [comment]
This issue has been closed because it doesn't have recent activity. Thank you for your contributions.
