### ISSUE TITLE
The sent data to the hub cannot be read from Stream Analytics 

### ISSUE THREAD

**Issue by michaelnemtsev** [Azure/azure-event-hubs-node#132]
**Describe the bug**
I've been using SimpleSender.ts example to send data to an event hub, which were successfully
however, this information cannot be read from Stream Analytics connected to EventHub. Simple action of "Sample Data" returns the error and data is not visibile

It appears that the follow code that sends the event to the hub sends it in the wrong format
 const data: EventData = {
    body: "Hello World!!"
  };
  const delivery = await client.send(data);

**To Reproduce**
1. Create a new Stream Analytics
2. Create a new Input job connecting to the existing hub with active data using JSON format 
3. Try "Sample Data" for the new connection using the right timeslot where data exist
4. Error will be generated that data cannot be read

**Expected behavior**
The data is read successuflly

**Package-name**: **azure-event-hubs** | **azure-event-processor-host**
**Package-version**: 
**node.js version**:
**OS name and version**:

**Additional context**

**Comment by SplitThePotCyrus** [comment]
I think this is due to the fact that SA expects the payload of the data to be JSON, in the example you've provided it is a string. 

Try this instead

const data: EventData = {
body: { "message": "Hello World!!" }
};

**Comment by amarzavery** [comment]
Hi @michaelnemtsev thanks for filing the issue. I think stream analytics needs data in json format. So if you send the body as`JSON.stringify("Hello World!!")` then it should work

**Comment by amarzavery** [comment]
We will update our examples with a comment that says for interacting with Stream Analytics make sure that the body property of EventData is a json object.

**Comment by michaelnemtsev** [comment]
@SplitThePotCyrus this worked. I appreciate if someone updates the examples accordingly and use {} for the body

**Comment by amarzavery** [comment]
This problem is Stream Analytics specific. Eventhubs as a service will accept any type of body for the message. We will document this in our examples to make it clear

**Comment by amarzavery** [comment]
All the [examples for send](https://github.com/Azure/azure-event-hubs-node/tree/master/client/examples), now have a comment to send a JSON object, if the EventHub is being used in conjunction with StreamAnalytics.
