### ISSUE TITLE
Numeric zero is treated as undefined in client.receive(...) method

### ISSUE THREAD

**Issue by arulselvam** [Azure/azure-event-hubs-node#155]
`client.receive(...)` throws ArgumentError: No starting position was set in the EventPosition.
 when we pass numeric 0 for `EventPosition.fromOffset(...)` or for `EventPosition.fromSequenceNumber(…)`.
Observed similar issue if we pass numeric 0 for partitionId to `client.receive()` method

**Package-name**: **@azure/event-hubs****Package-version**: 
**node.js version**: 10.0.0

**Comment by amarzavery** [comment]
@arulselvam - New version of `@azure/event-hubs: 1.0.3` has been published which fixes this issue and some other issues as well.
