### ISSUE TITLE
Support for sastoken

### ISSUE THREAD

**Issue by Mgccon** [Azure/azure-event-hubs-node#17]
Are you considering adding support for the SAStoken for this library?
Example:
var client = EventHubClient.EventHubClient.fromConnectionString('Endpoint=sb://my-hub.servicebus.windows.net/;SharedAccessSignature=' +  encodeURIComponent('sr=sb%3a%2f%2fmy-hub.servicebus.windows.net%2fdatacollectoroutbox%2fpublishers%2ffb5ec0e2-da48-43b2-9abf-dee0388a1457&sig=XXXXXXXXXXXXXXX&se=4640345124&skn=SendAccessPolicy'), 'queue')

**Comment by amarzavery** [comment]
@Mgccon - We do support sas token auth now. We have a new preview version "0.1.0" of the event hubs node.js client. This client was re-written from scratch. Please try the new version and let us know if you still see issues. You can find examples over [here](https://github.com/Azure/azure-event-hubs-node#examples).
