### ISSUE TITLE
Partition key not preserved on send

### ISSUE THREAD

**Issue by kurtb** [Azure/azure-event-hubs-node#20]
I'm attempting to follow https://github.com/Azure/azure-event-hubs-node/tree/master/send_receive and do a send/receive with a partition key set. Debugging the code shows that x-opt-partition-key is being set on the message. But upon receipt the partitionKey is undefined. And as such the messages are distributed across the partitions. Did I miss a code/configuration/etc... step or is this a bug in the library?

**Comment by kurtb** [comment]
FYI this appears to be an issue with the name of the message annotations option to the amqp10 library. Not sure when if/when it changed but it's now messageAnnotations and not annotations. After that small change everything seems to be working.

I opened a pull request with the fix #21

**Comment by pierreca** [comment]
Fix has been merged and package has been released with version 0.0.7
