### ISSUE TITLE
systemProperties is empty object in 0.0.8

### ISSUE THREAD

**Issue by ha62791** [Azure/azure-event-hubs-node#35]
Node version: 6.10.0
azure-event-hubs: 0.0.8

message.systemProperties is empty object in 0.0.8
It is not empty in 0.0.4

**Comment by jantielens** [comment]
Noticed this as well ... is there any fix?

**Comment by amarzavery** [comment]
@ha62791 @jantielens  - We have a new preview version "0.1.0" of the event hubs node.js client. This client was re-written from scratch. Please try the new version and let us know if you still see issues. You can find examples over [here](https://github.com/Azure/azure-event-hubs-node#examples).
