### ISSUE TITLE
The message container is being closed (10398).

### ISSUE THREAD

**Issue by willin** [Azure/azure-event-hubs-node#37]
Azure Eventhubs » 0.12.0: http://mvnrepository.com/artifact/com.microsoft.azure/azure-eventhubs/0.12.0

 

refs:

- https://github.com/Azure/azure-event-hubs-java/issues/67
- https://github.com/Azure/azure-event-hubs-java/pull/78

**Comment by amarzavery** [comment]
This looks like a java event hub issue. Hence closing it. We have a new preview version "0.1.0" of the event hubs node.js client. This client was re-written from scratch. Please try the new version and let us know if you still see issues. You can find examples over [here](https://github.com/Azure/azure-event-hubs-node#examples).
