### ISSUE TITLE
Having Problems with Sender

### ISSUE THREAD

**Issue by iremkorkmaz** [Azure/azure-event-hubs-node#39]
I have a streamed data transferred to Azure Event Hub via my server. 
Problem I am facing is I create a client and sender everytime I receive a data from my server to transfer to Azure Event Hub but the error I get is : 
**AmqpOverCapacityError: Out of available handles (Max = 255)]**

When I try to close the client after the data is sent the error I get is :
**Unhandled rejection AmqpProtocolError: amqp:link:detach-forced:detach-forced**

I am not sure if this is an issue or an error caused by me but I am trying to figure out the best solution. 

If you can help me with that, I will be pleased.

**Comment by amarzavery** [comment]
@iremkorkmaz - We have a new preview version "0.1.0" of the event hubs client. This client was written from scratch all up. Please try the new version and let us know if you still see issues. You can find examples over [here](https://github.com/Azure/azure-event-hubs-node#examples).
