### ISSUE TITLE
The link 'G25:30407932:/hub2/Partitions/0_3028ebb3-62b8-429e-ba29-ff19bb19f209' is force detached by the broker due to errors occurred in publisher(link39916690)

### ISSUE THREAD

**Issue by abraxas93** [Azure/azure-event-hubs-node#40]
Hi! Time after time i catch an error. 
{"message":"The link 'G25:30407932:/hub2/Partitions/0_3028ebb3-62b8-429e-ba29-ff19bb19f209' is force detached by the broker due to errors occurred in publisher(link39916690). Detach origin: AmqpEventHubPublisher.IdleTimerExpired: Idle timeout: 00:30:00. TrackingId:de0acc420000665a0261149259c008bd_G25_B23, SystemTracker:cryptohub:eventhub:hub2~16383, Timestamp:9/18/2017 10:51:19 PM","stack":"Error: The link 'G25:30407932:/hub2/Partitions/0_3028ebb3-62b8-429e-ba29-ff19bb19f209' is force detached by the broker due to errors occurred in publisher(link39916690). Detach origin: AmqpEventHubPublisher.IdleTimerExpired: Idle timeout: 00:30:00. TrackingId:de0acc420000665a0261149259c008bd_G25_B23, SystemTracker:cryptohub:eventhub:hub2~16383, Timestamp:9/18/2017 10:51:19 PM\n    at Object.translateError [as translate] (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\azure-event-hubs\\lib\\errors.js:37:15)\n    at SenderLink.EventHubSender.onErrorReceived (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\azure-event-hubs\\lib\\sender.js:27:39)\n    at emitOne (events.js:101:20)\n    at SenderLink.emit (events.js:188:7)\n    at SenderLink.Link._detached (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\amqp10\\lib\\link.js:221:10)\n    at SenderLink._detached (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\amqp10\\lib\\sender_link.js:236:41)\n    at SenderLink.Link._detachReceived (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\amqp10\\lib\\link.js:204:8)\n    at Session._processDetachFrame (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\amqp10\\lib\\session.js:335:45)\n    at Session._processFrame (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\amqp10\\lib\\session.js:302:61)\n    at Connection._processFrameEH (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\amqp10\\lib\\session.js:186:49)\n    at emitOne (events.js:101:20)\n    at Connection.emit (events.js:188:7)\n    at Connection._receiveAny (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\amqp10\\lib\\connection.js:426:12)\n    at Connection._receiveData (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\amqp10\\lib\\connection.js:357:8)\n    at .<anonymous> (\\\\100.79.154.12\\volume-19-default\\6fbefa519d815ec9c983\\1918a609e6dd4a39906d5e11ef821ab1\\site\\wwwroot\\node_modules\\amqp10\\lib\\connection.js:515:38)\n    at emitOne (events.js:96:13)","transport":{"name":"AmqpProtocolError","message":"amqp:link:detach-forced:The link 'G25:30407932:/hub2/Partitions/0_3028ebb3-62b8-429e-ba29-ff19bb19f209' is force detached by the broker due to errors occurred in publisher(link39916690). Detach origin: AmqpEventHubPublisher.IdleTimerExpired: Idle timeout: 00:30:00. TrackingId:de0acc420000665a0261149259c008bd_G25_B23, SystemTracker:cryptohub:eventhub:hub2~16383, Timestamp:9/18/2017 10:51:19 PM","condition":"amqp:link:detach-forced","description":"The link 'G25:30407932:/hub2/Partitions/0_3028ebb3-62b8-429e-ba29-ff19bb19f209' is force detached by the broker due to errors occurred in publisher(link39916690). Detach origin: AmqpEventHubPublisher.IdleTimerExpired: Idle timeout: 00:30:00. TrackingId:de0acc420000665a0261149259c008bd_G25_B23, SystemTracker:cryptohub:eventhub:hub2~16383, Timestamp:9/18/2017 10:51:19 PM","errorInfo":{}},"codeBlock":"HUB2: Partcion 0","level":"error","timestamp":"2017-09-18T22:51:18.648Z"}
Does anybody know what is wrong? And how i can handle this error?

**Comment by amarzavery** [comment]
@abraxas93  - We have a new preview version "0.1.0" of the event hubs client. This client was re-written from scratch. Please try the new version and let us know if you still see issues. You can find examples over [here](https://github.com/Azure/azure-event-hubs-node#examples).
