### ISSUE TITLE
reverse proxy

### ISSUE THREAD

**Issue by adisD** [Azure/azure-event-hubs-node#45]
the sender part of code is running on the on-premises server deployed behind a reverse proxy.

My assumption is that above is causing "unhandled rejection amqp disconnected error"?

On the other side I am aware of how the http package exposes an agent property that expects http-proxy-agent.

Is there similar to above in EventHubsClient?

**Comment by adisD** [comment]
got motivated by comment on https://github.com/Azure/azure-event-hubs-dotnet/issues/210 where the connection string extends with ProxyAddress. Unfortunately have not helped as same error remained the same.

**Comment by ramya-rao-a** [comment]
This issue has been closed because it needs more information and has not had recent activity. Thank you for your contributions.
