### ISSUE TITLE
NodeJS: express and eventhub SDK

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-node#5]
_From @ThomasAnnerel on June 1, 2016 6:30_

Dear

We are using an Azure App Service to push messages on a eventhub (+- 2,5 milj messages/hour). The thing we are struggling with a lot is finding a best practice for reusing clients and senders and how to host it in express.

Possibilites:
- new client and sender on every request.
- keep the client alive .
- keep the client and sender alive

I think we are sometimes hitting the connection limit on ServiceBus (+- 5000 connections)

_Copied from original issue: Azure/azure-event-hubs#163_

**Comment by amarzavery** [comment]
This would be a good sample to demonstrate the power of EventHubs and the new version of node.js sdk. We have tested the new version and the senders and receivers stay alive for longer durations (How long is long enough? - can be subjective). It should be fairly  simple to put together an express based app and the new EH sdk.

**Comment by AlexGhiondea** [comment]
Closing this for now.
