### ISSUE TITLE
Add browser support for Event Hubs

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-event-hubs-node#56]
The [eventhub viewer website](https://github.com/shkreza/eventhub-viewer) that someone created. It should be good to take a look at.
This is a meta issue that has references to similar issue.
- https://github.com/Azure/azure-event-hubs-node/issues/11
- https://github.com/Azure/azure-event-hubs-node/issues/2
- https://github.com/Azure/azure-event-hubs-node/issues/81

**Comment by AlexGhiondea** [comment]
This is tracked by https://github.com/Azure/azure-sdk-for-js/issues/1056.
