### ISSUE TITLE
Version "0.1.2" creates incompatible messages, breaking change on the data format

### ISSUE THREAD

**Issue by SplitThePotCyrus** [Azure/azure-event-hubs-node#60]
I'm currently testing out using Event Hub with Stream Analytics.
I noticed that the change from **0.0.8** to **0.1.2** causes the sent events not to be identified correctly by Stream Analytics and therefore getting dropped.

I've tried many variances, `JSON.stringify()` the object added to `data` property or even creating `Buffer`. Nothing helps.

Also the received events from Event Hub, that was sent using 0.0.8, are not parsed correctly.
```
   body: Section {typecode: 117, content: Buffer(145), multiple: undefined}
   content:Buffer(145) [123, 34, 105, …]
   multiple:undefined
   typecode:117
```

I understand that the API has breaking changes, but having breaking changes in data is not so nice :)

~~Also 0.1.2 < 0.8.0, this is a very confusing versioning logic in this cases since 0.1.2 is newer than 0.8.0~~

**Comment by amarzavery** [comment]
> I noticed that the change from **0.0.8 to 0.1.2** causes the sent events not to be identified correctly by Stream Analytics and therefore getting dropped.
> I've tried many variances, JSON.stringify() the object added to data property or even creating Buffer. Nothing helps.

If I understand correctly, you want to send an event to Stream Analytics that was received from EventHub, correct? OR Are you saying that you are unable to send data to EventHub?

Can you please provide a sample of the data that you would want to send to (I guess stream analytics)?

The previous version before  0 **.1.** 0 was 0 **.0.** 8. Here is the history of available versions on npm. We have **never** shipped a `0.8.0` version.
```
npm show azure-event-hubs@* version
azure-event-hubs@0.0.1 '0.0.1'
azure-event-hubs@0.0.2 '0.0.2'
azure-event-hubs@0.0.3 '0.0.3'
azure-event-hubs@0.0.4 '0.0.4'
azure-event-hubs@0.0.5 '0.0.5'
azure-event-hubs@0.0.6 '0.0.6'
azure-event-hubs@0.0.7 '0.0.7'
azure-event-hubs@0.0.8 '0.0.8'
azure-event-hubs@0.1.0 '0.1.0'
azure-event-hubs@0.1.1 '0.1.1'
azure-event-hubs@0.1.2 '0.1.2'
```

> Also the received events from Event Hub, that was sent using 0.8.0, are not parsed correctly.

I agree about that. The new underlying library (rhea) that we depend on does type encoding differently. We can add a helper function to the EventData object that can make a best attempt at deserialize the body correctly.

I think the helper function would be something like below: 
```js
function tryConvertEventDataBodyToString(eventData) {
let result;
  if (eventData) {
    if (typeof eventData.body === "string")
    result = eventData.body;
  else if (eventData.body.content)
    result = eventData.body.content.toString("utf8");
  else if (Buffer.isBuffer(eventData.body))
    result = eventData.body.toString("utf8");
  }
  console.log("The stringified body is: ", result);
}
```
Let me know if that works..

**Comment by SplitThePotCyrus** [comment]
Oh sorry my bad regarding the version numbers, got a bit confused by the tags in GitHub.

I am able to send data to EventHub, but the Stream Analytics Job which has that same EventHub as source cannot parse/understand the format of the data when sent from the latest version of this lib. 

Even sampling the data for performing offline testing of SA scripts does not work for the data sent by the latest version of this lib.

Am I making any sense?

**Comment by amarzavery** [comment]
Can you share the snippet from your script that is sending data to the EventHub?

Make sure that you are sending the data in the **body property** of the event to be sent.
```js
  const data = { body: "Hello World 1", message_id: "343-0909-5454-23423-54543" };
// message_id in the above object is optional.
  const delivery = await client.send(data);
```
You can take a look at an example over [here - ts version](https://github.com/Azure/azure-event-hubs-node/blob/master/examples/simpleSender.ts#L11), [js-version](https://github.com/Azure/azure-event-hubs-node/blob/master/examples/js/examples/simpleSender.js#L19).

**Comment by amarzavery** [comment]
I modified this [sample script](https://github.com/Azure/azure-event-hubs-node/blob/master/examples/simpleSendReceive.ts#L27) to send and receive the sample data that you provided and it worked well.

This was the modification
```js
const object = {
      "id": "7a63aaa394c74c1182308f19d4c4cb79",
      "name": "John",
      "data": "{}",
      "version": 1
    };
await client.send({ body: object }, ids[i]);
```

Here is the output:
```
$ ts-node examples/simpleSendReceive.ts
>>>> Hub:
 { path: 'f****',
  createdAt: 2018-04-22T17:44:51.083Z,
  partitionCount: 3,
  partitionIds: [ '0', '1', '2' ],
  type: 'com.microsoft:eventhub' }
***********Created receiver 0
***********Created sender 0 and sent the message...
>>> EventDataObject:  { body:
   { id: '7a63aaa394c74c1182308f19d4c4cb79',
     name: 'John',
     data: '{}',
     version: 1 },
  _raw_amqp_mesage: {"message_annotations":{"x-opt-sequence-number":3856207,"x-opt-offset":"51552320496","x-opt-enqueued-time":1524955958475},"body":{"id":"7a63aaa394c74c1182308f19d4c4cb79","name":"John","data":"{}","version":1}},
  annotations:
   { 'x-opt-sequence-number': 3856207,
     'x-opt-offset': '51552320496',
     'x-opt-enqueued-time': 1524955958475 },
  sequenceNumber: 3856207,
  enqueuedTimeUtc: 2018-04-28T22:52:38.475Z,
  offset: '51552320496' }
>>>> ### Actual message: { id: '7a63aaa394c74c1182308f19d4c4cb79',
  name: 'John',
  data: '{}',
  version: 1 }
***********Created receiver 1
***********Created sender 1 and sent the message...
>>> EventDataObject:  { body:
   { id: '7a63aaa394c74c1182308f19d4c4cb79',
     name: 'John',
     data: '{}',
     version: 1 },
  _raw_amqp_mesage: {"message_annotations":{"x-opt-sequence-number":1945,"x-opt-offset":"235992","x-opt-enqueued-time":1524955968321},"body":{"id":"7a63aaa394c74c1182308f19d4c4cb79","name":"John","data":"{}","version":1}},
  annotations:
   { 'x-opt-sequence-number': 1945,
     'x-opt-offset': '235992',
     'x-opt-enqueued-time': 1524955968321 },
  sequenceNumber: 1945,
  enqueuedTimeUtc: 2018-04-28T22:52:48.321Z,
  offset: '235992' }
### Actual message: { id: '7a63aaa394c74c1182308f19d4c4cb79',
  name: 'John',
  data: '{}',
  version: 1 }
***********Created receiver 2
***********Created sender 2 and sent the message...
>>> EventDataObject:  { body:
   { id: '7a63aaa394c74c1182308f19d4c4cb79',
     name: 'John',
     data: '{}',
     version: 1 },
  _raw_amqp_mesage: {"message_annotations":{"x-opt-sequence-number":1917,"x-opt-offset":"231616","x-opt-enqueued-time":1524955978116},"body":{"id":"7a63aaa394c74c1182308f19d4c4cb79","name":"John","data":"{}","version":1}},
  annotations:
   { 'x-opt-sequence-number': 1917,
     'x-opt-offset': '231616',
     'x-opt-enqueued-time': 1524955978116 },
  sequenceNumber: 1917,
  enqueuedTimeUtc: 2018-04-28T22:52:58.116Z,
  offset: '231616' }
### Actual message: { id: '7a63aaa394c74c1182308f19d4c4cb79',
  name: 'John',
  data: '{}',
  version: 1 }
$
```

I have not tested sending this event to stream analytics in this script. So cannot tell much about that part.
However, I was able to send and receive the sample object correctly to/from every partition in the event hub.

**Comment by SplitThePotCyrus** [comment]
I think you might easily be able to replicate and get sample data just by using version 0.0.8 npm package and ingesting data into eventhub.

However this is the data response caught in developer tools:

Range having data sent with version 0.0.8
```json
{
    "result": {
        "status": "ReadAllEventsInRange",
        "error": null,
        "eventsDownloadUrl":
            "https://nrtprodwestorage.blob.core.windows.net/...",
        "lastArrivalTime": "2018-04-28T23:30:29.098Z",
        "diagnostics": null,
        "fileContent":
            "[{\"id\":\"7a63aaa394c74c1182308f19d4c4cb78\",\"name\":\"John\",\"data\":\"{}\",\"version\":1}, ...]"
    },
    "retryAfter": 0,
    "isCompleted": true,
    "callbackEndpoint": "api/Inputs/GetSampleInputForQueryOperationStatus",
    "operationId": null
}
```

Range having data sent with version 0.1.2 (masked out some details)
```json
{
    "result": {
        "status": "NoEventsFoundInRange",
        "error": null,
        "eventsDownloadUrl": "",
        "lastArrivalTime": "2018-04-28T23:30:29.098Z",
        "diagnostics": [
            "While sampling data, no data was received from '2' partitions.",
            "Could not deserialize the input event(s) from resource 'Partition: [1], Offset: [13576], SequenceNumber: [59]' as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format",
            "Could not deserialize the input event(s) from resource 'Partition: [1], Offset: [13792], SequenceNumber: [60]' as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format",
            "Could not deserialize the input event(s) from resource 'Partition: [1], Offset: [13920], SequenceNumber: [61]' as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format",
            "Could not deserialize the input event(s) from resource 'Partition: [0], Offset: [13904], SequenceNumber: [58]' as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format",
            "Could not deserialize the input event(s) from resource 'Partition: [0], Offset: [14256], SequenceNumber: [59]' as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format",
            "Could not deserialize the input event(s) from resource 'Partition: [0], Offset: [14472], SequenceNumber: [60]' as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format",
            "Could not deserialize the input event(s) from resource 'Partition: [0], Offset: [14600], SequenceNumber: [61]' as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format",
            "Could not deserialize the input event(s) from resource 'Partition: [0], Offset: [14816], SequenceNumber: [62]' as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format",
            "Could not deserialize the input event(s) from resource 'Partition: [0], Offset: [15168], SequenceNumber: [63]' as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format"
        ],
        "fileContent": null
    },
    "retryAfter": 0,
    "isCompleted": true,
    "callbackEndpoint": "api/Inputs/GetSampleInputForQueryOperationStatus",
    "operationId": null
}
```

**Comment by amarzavery** [comment]
Thanks for sending this info. I looked at the networking tab using the developer tools of the browser and could see the same info. It would have been so easy had they provided a stringified form of the data they received from the EventHub that caused problems during deserialization.

I will have to get in touch with folks from Stream Analytics to actually see what data are they receiving from the EventHub. My guess is that it would be the similar stuff that I provided in the helper function in [this comment](https://github.com/Azure/azure-event-hubs-node/issues/60#issuecomment-385208558).

**Comment by amarzavery** [comment]
Ok, So I was able to get this working by making some modification.
I will have to dig a little deeper and make sure that encoding and decoding is done inside the library without you having to worry about it.

```js
const rhea = require("rhea"); 
.....
const object = {
      "id": "7a63aaa394c74c1182308f19d4c4cb79",
      "name": "John" + new Date().toString(),
      "data": "{}",
      "version": 1
    };
    await client.send({ body: rhea.message.data_section(Buffer.from(JSON.stringify(object), "utf8")) }, ids[i]);
// Dont worry about the second parameter. I am sending a message to a specific partition.
```

For reference I modified the same example [simpleSendReceive.ts](https://github.com/Azure/azure-event-hubs-node/blob/master/examples/simpleSendReceive.ts#L27).

Here is the sample output from an eventhub input source:
```json5
[
  {
    "id": "7a63aaa394c74c1182308f19d4c4cb79",
    "name": "John",
    "data": "{}",
    "version": 1,
    "EventProcessedUtcTime": "2018-04-30T15:46:06.2001771Z",
    "PartitionId": 1,
    "EventEnqueuedUtcTime": "2018-04-30T15:45:05.1030000Z"
  }
]
```

**Comment by amarzavery** [comment]
"azure-event-hubs" version 0.2.0 has been published with the fix.
