### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by yanisIk** [Azure/azure-event-hubs-node#71]
How to reproduce:

- 3 connected clients
- Sending events to all of them
- Warning appears at the begining
- I have no other EventEmitter in my code

Node: 10.0.0
Npm: 5.6.0
tsc: 2.7.2
azure-event-hubs: 0.1.2

Here's the stack trace using `node --trace-warnings`

```
(node:15668) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 released listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:244:19)
    at Sender.addListener (events.js:261:10)
    at Promise (C:\...\node_modules\azure-event-hubs\dist\lib\eventHubSender.js:231:30)
    at new Promise (<anonymous>)
    at EventHubSender._trySend (C:\...\node_modules\azure-event-hubs\dist\lib\eventHubSender.js:175:34)
    at EventHubSender.<anonymous> (C:\...\node_modules\azure-event-hubs\dist\lib\eventHubSender.js:68:35)
    at Generator.next (<anonymous>)
    at C:\...\node_modules\azure-event-hubs\dist\lib\eventHubSender.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (C:\...\node_modules\azure-event-hubs\dist\lib\eventHubSender.js:5:12)
```

**FIX: Make sure to await on the client.send() method.**

**Comment by amarzavery** [comment]
Can you share the code snippet? If you are running the sends in a loop, it looks like you did not await on sending the messages.

**Comment by yanisIk** [comment]
Right now I'm subscribing to a websocket and sending wathever I receive from it without waiting for the promise to resolve (client.send)

What happens when I wait for the client.send() ? Is it waiting for the response from EventHubs or something else ? Because if it's the first case, then it is sending events synchronously and this would be very slow for use cases where you need to send hundreds of events per second.

**Comment by amarzavery** [comment]
If you are using an async function then you can await inside a for loop. Take a look at an example over [here](https://github.com/Azure/azure-event-hubs-node/blob/master/client/tests/receiver.spec.ts#L43-L49).

**Comment by amarzavery** [comment]
The promisified send is wrapping the event handler underneath where it adds a listener for every attempt to send and removes it once it gets the accepted, rejected, modified or released event. Since you are not waiting on the promise to complete, too many event handlers are being attached and they are removed at a slower rate. If an error is received that is retryable then it will attempt to retry the send.

**Comment by yanisIk** [comment]
Yeah you were right, I wasn't waiting on purpose to get the max throughput, now I do and no more warnings.
I will edit my issue and include the answer.

But I still have a question: Is the sending process synchronous or async ? Is it waiting for a message to deliver before sending the next one ?

The C# library has two modes: sync and async. But here I don't know if waiting on the client.send() makes it wait on message delivery or not.

This is very important because it can drastically change the throughput.

Thanks !
