### ISSUE TITLE
Partitions not associated correctly

### ISSUE THREAD

**Issue by yanisIk** [Azure/azure-event-hubs-node#73]
I know this is an already known issue by the developer(s) .

This issue is opened to track the progress because this feature is crucial and some people like me need it to make their parallelized queries work correctly (PARTITION BY when grouping is not possible right now because of this issue)

Thanks.

**Comment by amarzavery** [comment]
related issue https://github.com/Azure/azure-event-hubs-node/issues/72

**Comment by amarzavery** [comment]
@yanisIk - This issue has been fixed by #74. Please install version 0.2.2 of azure-event-hubs and you should be good to go!
