### ISSUE TITLE
Sending a message in the client.receive()

### ISSUE THREAD

**Issue by jeffaknine** [Azure/azure-event-hubs-node#77]
Hi, i have the following issue: 
My web api is running an Event hub client. I am able to receive messages from my devices. 
To send messages to the web api i'm using azure-iothub and azure-iot-common.
The problem is when i receive a message on the web api and that i want to send a message back to the device, the device never gets it.
Here is my code:

WebApi:

    const { EventHubClient, EventPosition } = require('azure-event-hubs');
    var connectionString = 'myConnectionString'
    var sendingClient = require('../azure/sendingClient')
    
    async function main() {
        sendingClient.sendMessage('raspberry',{},"allDevices")  //The raspberry receives this  
        const client = await 
        EventHubClient.createFromIotHubConnectionString(connectionString);
    
        const onError = (err) => {
            console.log("An error occurred on the receiver ", err);
        };
    
        const onMessage = (msg) => {
            console.log(msg.body);
            sendingClient.sendMessage('raspberry',{},"allDevices")// the raspberry doesn't receive this
        };

        const receiveHandler = client.receive("1", onMessage, onError, { 
            eventPosition: EventPosition.fromEnqueuedTime(Date.now()) 
        });

      await receiveHandler.stop();
      await client.close();
    }

    main().catch((err) => {
        console.log(err);
    });

Sending client:
    
    var Client = require('azure-iothub').Client;
    var Message = require('azure-iot-common').Message;

    var connectionString = 'myConnectionString'

    var sendingClient = Client.fromConnectionString(connectionString);

    exports.sendMessage = (targetDevice, content, messageId) => {
        sendingClient.open(function (err) {
            if (err) {
                console.error('Could not connect: ' + err.message);
            } else {
                console.log('Service client connected');
                var message = new Message(content);
                message.ack = 'full';
                message.messageId = 'message'
                message.properties.add('message',messageId)
                console.log('Sending message: ' + message.getData());
                console.log('Sending message to : ' + targetDevice);            
                sendingClient.send(targetDevice, message,);
            }
        });
    }

Receiver on the device:

    var iothub = require('azure-iothub');
    var Protocol = require('azure-iot-device-mqtt').Mqtt;
    var Client = require('azure-iot-device').Client;
    var Message = require('azure-iot-device').Message;
    var client = Client.fromConnectionString(connectionString, Protocol)
	client.open((err) => {
        if (err) console.error('Could not connect: ' + err.message)
        else {
            client.on('message', (msg) => {
                switch (msg.properties.propertyList[1].value) {
                    case 'allDevices':
                        devices = JSON.parse(msg.data.toString())
                        response(devices) //passing the message content
                }
            });

            client.on('error', (err) => {
                console.error(err.message);
            });

            client.on('disconnect', () => {
                clearInterval(sendInterval);
                client.removeAllListeners();
                client.open(connectCallback);
            });
        }
    })

**Comment by amarzavery** [comment]
@jeffaknine - I see that you are stopping the receiver and closing the client. I think that is the problem.

The receive() method on the client is not awaitable. It will add onMessage and onError handlers to the EH client receiver. 
After that it will proceed to the next line that is `await receiveHandler.stop()`. I would recommend to comment out receiveHandler.stop() and client.close() calls and try again.

**Comment by amarzavery** [comment]
@jeffaknine - Did the above comment help resolve the issue?
