### ISSUE TITLE
NodeJS: Node client's Connection String should support "HostName" keyword

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-node#8]
_From @hmlam on January 26, 2016 19:32_

In .Net client the connection string can have the following keyword for specifying connection endpoints:
1. Endpoint=url1[;url2]
2. HostName=host1[;host2]

The difference is that Endpoint requires a URL format, while HostName has no such requirement and internally will create the SB:// URL from hostname.

Event though the original requirement comes from IoT, HostName keyword is designed to be supported by all SB scenario in mind, and so the NodeJS library should also support it.

_Copied from original issue: Azure/azure-event-hubs#16_

**Comment by amarzavery** [comment]
@hmlam - We have a new preview version "0.1.0" of the event hubs client. This client was written from scratch all up. Please try the new version and let us know if you still see issues. You can find examples over [here](https://github.com/Azure/azure-event-hubs-node#examples).
