### ISSUE TITLE
Receiving all messages from storage after returning context.checkpoint()

### ISSUE THREAD

**Issue by HaykHayrapetyan** [Azure/azure-event-hubs-node#80]
//Receiver.js
```js
async function main() {
  // Create the Event Processo Host
  const eph = EventProcessorHost.createFromConnectionString(
    EventProcessorHost.createHostName("my-host"),
    storageCS,
    ehCS,
    {
      eventHubPath: path
    }
  );

  // Message event handler
  const onMessage = (context/*PartitionContext*/, data /*EventData*/) => {
    console.log(">>>>> Rx message from ", context.partitionId, ': ', data.body);
    //console.log('context', context)
    return context.checkpoint();
  };
  // Error event handler
  const onError = (error) => {
    console.log(">>>>> Received Error: %O", error);
  };
  // Register the event handlers
  eph.on(EventProcessorHost.message, onMessage);
  eph.on(EventProcessorHost.error, onError);
  // start the EPH
  await eph.start();
}

main().catch((err) => {
  console.log(err);
});
```

After receiving all events once, I checkpoint them. But after every restart of node instance it receives them once more. How can I checkpoint the offset??

**Comment by Grigsuv** [comment]
I have the same problem

**Comment by HaykHayrapetyan** [comment]
@amarzavery here is one of the info's stored in the storage:

{"partitionId":"1","owner":"my-host-b77442e5-7870-4d42-a834-9595b3a74b05","token":"53d17dad-6fad-458b-ba8a-11cc689c3fd3","epoch":1528209623048,"sequenceNumber":1,"offset":"88"}

Is this the way it was supposed to be stored?

**Comment by amarzavery** [comment]
Okay So I figured what is going on... 
The checkpoint info is stored in the blob container. The name of the blob container is the name of the EPH. In the above sample, a new blob container will be created every time the sample is run (i.e. once all the messages are received, you close the script and then run it again at a later time). If you pass the name of the previously created blob container, then the EPH will not read all the messages from start. It will read the checkpoint info if it exists in the blob and read messages after that point..

This parameter `EventProcessorHost.createHostName("my-host"),` should be replaced by the name of the previously created container name (which can be found from the portal). 

This is not very obvious and should definitely be handled in a better way then what we are doing currently.. 

If you have any suggestion to handle this in a better way then please feel free to share them.

**Comment by amarzavery** [comment]
Actually, I have built-in provision to provide a `leaseContainerName`. You can find all the optional parameters over [here](https://github.com/Azure/azure-event-hubs-node/blob/master/processor/lib/eventProcessorHost.ts#L76).

**Comment by amarzavery** [comment]
I have updated the [sample in README](https://github.com/Azure/azure-event-hubs-node/blob/master/processor/README.md#usage) that provides a leaseContainerName. This should make it clear.

**Comment by HaykHayrapetyan** [comment]
Thank you @amarzavery, so I was just supposed to store the hostname of the blob storage and put as an argument in EventProcessorHost.createHostName() function. Problem is solved!

**Comment by HaykHayrapetyan** [comment]
@amarzavery  It seemed to work fine as the receiver got the old messages only once(when I first ran it, all messages were checkpointed and I didn't get the new ones). However after process restart, I don't get new messages sent to eventhub.

**Comment by amarzavery** [comment]
fixed by https://github.com/Azure/azure-event-hubs-node/pull/82
