### ISSUE TITLE
ephost.stop() fails with error if messages are still being received

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-node#9]
_From @timfpark on February 15, 2016 23:40_

If messages are still being received from the AMQP connection, calling ephost.stop() fails with the error:

/Users/tim/dev/rhom/enrichProcessor/node_modules/tim-azure-event-hubs/node_modules/amqp10/lib/link.js:101
  this.session.connection.sendFrame(attachFrame);
                         ^

TypeError: Cannot read property 'sendFrame' of undefined
    at ReceiverLink.Link.attach (/Users/tim/dev/rhom/enrichProcessor/node_modules/tim-azure-event-hubs/node_modules/amqp10/lib/link.js:101:26)
    at ReceiverLink.Link._attemptReattach (/Users/tim/dev/rhom/enrichProcessor/node_modules/tim-azure-event-hubs/node_modules/amqp10/lib/link.js:204:8)
    at null._onTimeout (/Users/tim/dev/rhom/enrichProcessor/node_modules/tim-azure-event-hubs/node_modules/amqp10/lib/link.js:192:10)
    at Timer.listOnTimeout (timers.js:92:15)

This can be repro'ed with the sample on the README.md and a timeout that is large enough that the AMQP connection is established and small enough that you haven't yet processed all of them from your Event Hub.

_Copied from original issue: Azure/azure-event-hubs#46_

**Comment by pierreca** [comment]
Hi @timfpark 
A couple of things:
- this issue seem related directly to `amqp10` and some reattach logic that has significantly changed with the new releases. I'd be curious to know if you're still hitting this issue.
- event process host work was never entirely merged (started with @noodlefrenzy on the old repo and was not ported here). This SDK is maintained by a couple of volunteers (mostly just me right now) and not an official one (unlike C# and .NET). If you're interested in EPH support, may I suggest you contribute this directly back into this repo? I'll work with you to make sure it ships.
- please refrain from publishing alternate packages on NPM that basically have the same name and package description: it's confusing for customers (referring to this: https://www.npmjs.com/package/tim-azure-event-hubs). As "unofficial" as this SDK, repo and associated package are, it's still maintained and published according to the Microsoft OSS guidelines. We want customers to be able to easily identify which one should be used. This allows us (and @jtaubensee) to gauge the interest of the community and appropriately allocate resources.

Closing as this seem out of date now. Thanks!
